### ISSUE TITLE
Binary XML file line #36: Error inflating class Button

### ISSUE THREAD

**Issue by jdsjlzx** [q805699513/PhotoPicker#1]
一直报错，log如下：
 UncaughtException detected: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.**.**/me.iwf.photopicker.PhotoPickerActivity}: android.view.InflateException: Binary XML file line #36: Error inflating class Button
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2351)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5308)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)
                                                                  Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class Button
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:767)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
                                                                     at me.iwf.photopicker.fragment.PhotoPickerFragment.onCreateView(PhotoPickerFragment.java:153)
                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2888)
                                                                     at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
                                                                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
                                                                     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
                                                                     at android.app.Activity.performStart(Activity.java:6065)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5308) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708) 
                                                                  Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 5
                                                                     at android.content.res.TypedArray.getColorStateList(TypedArray.java:427)
                                                                     at android.widget.TextView.<init>(TextView.java:994)
                                                                     at android.widget.Button.<init>(Button.java:111)
                                                                     at android.widget.Button.<init>(Button.java:107)
                                                                     at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:66)
                                                                     at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:62)
                                                                     at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
                                                                     at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1021)
                                                                     at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1080)
                                                                     at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
                                                                     at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:180)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:729)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
                                                                     at me.iwf.photopicker.fragment.PhotoPickerFragment.onCreateView(PhotoPickerFragment.java:153) 
                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189) 
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299) 
                                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
                                                                     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2888) 
                                                                     at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201) 
                                                                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603) 
                                                                     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
                                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236) 
                                                                     at android.app.Activity.performStart(Activity.java:6065) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5308) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)

**Comment by q805699513** [comment]
感谢你的修复反馈。

**Comment by MichealWangDan** [comment]
我也遇到了，怎么解决的？

**Comment by q805699513** [comment]
@

**Comment by q805699513** [comment]
@

**Comment by q805699513** [comment]
@MichealWangDan 好好看看文档，看看是不是忘了配置style
